# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

name: Build Development Images

on:
  push:
    branches-ignore:
      - main
      - staging

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/component-build-images.yml
    environment:
      name: development
    with:
      push: true
      version: ${{ github.sha }}
    secrets: inherit
