# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

name: Integration Tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  run-integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Build images
        run: make build

      - name: Run trace-based tests
        run: make run-tracetesting
