# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
#
name: Misspell

on:
  push:
    branches: [main, staging]
    paths:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.go'
      - '**/*.py'
      - '**/*.js'
      - '**/*.ts'
      - '**/*.java'
      - '**/*.yml'
      - '**/*.yaml'
  pull_request:
    branches: [main, staging]
    paths:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.go'
      - '**/*.py'
      - '**/*.js'
      - '**/*.ts'
      - '**/*.java'
      - '**/*.yml'
      - '**/*.yaml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  misspell:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: run misspell
        run: make misspell
