# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
#
name: Sanity Check

on:
  push:
    branches: [main, staging]
    paths:
      - 'internal/tools/sanitycheck.py'
      - 'src/**'
  pull_request:
    branches: [main, staging]
    paths:
      - 'internal/tools/sanitycheck.py'
      - 'src/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: run sanitycheck.py
        run: python3 ./internal/tools/sanitycheck.py
