# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

name: PR Checks

on:
  pull_request:
    branches:
      - staging
      - main

permissions:
  contents: read

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
    secrets: inherit

  lint-checks:
    uses: ./.github/workflows/lint-checks.yml
    secrets: inherit

  integration-tests:
    needs: unit-tests
    uses: ./.github/workflows/integration-tests.yml
    secrets: inherit
